import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import fs from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import { assertAllowedUrl, UrlAllowlistError } from "../security/url-allowlist.js";
import { safeBaseName, ensureInsideDir } from "./paths.js";
import type { InputFile } from "../types/contract.js";

export interface DownloadResult {
  localPath: string;
  bytes: number;
}

export class DownloadError extends Error {
  constructor(
    public readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = "DownloadError";
  }
}

interface DownloadOptions {
  maxBytes: number;
  timeoutMs: number;
  allowedHosts: readonly string[];
  isProduction: boolean;
}

/**
 * Stream a signed input URL to a local file inside `destDir`. The output
 * name is generated by the worker (never the caller). Enforces:
 *  - allowed hostnames
 *  - HTTPS in production
 *  - byte limit (aborts the stream past the cap)
 *  - request timeout
 *  - single redirect via `redirect: "follow"` cap of 3 handled by fetch
 */
export async function downloadInput(
  input: InputFile,
  destDir: string,
  opts: DownloadOptions,
): Promise<DownloadResult> {
  let url: URL;
  try {
    url = assertAllowedUrl(input.signedUrl, opts.allowedHosts, "download", opts.isProduction);
  } catch (err) {
    if (err instanceof UrlAllowlistError) {
      throw new DownloadError(err.code, err.message);
    }
    throw new DownloadError("invalid_download_url", "URL de download inválida.");
  }

  // Worker-owned local name — never uses caller's fileName as a path.
  const ext = extForMime(input.mimeType) ?? path.extname(safeBaseName(input.fileName)) ?? "";
  const localName = `${input.fileType}_${input.fileId}${ext}`;
  const dest = ensureInsideDir(destDir, localName);
  fs.mkdirSync(path.dirname(dest), { recursive: true });

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), opts.timeoutMs);

  let res: Response;
  try {
    res = await fetch(url, { redirect: "follow", signal: controller.signal });
  } catch (err) {
    clearTimeout(timer);
    if ((err as { name?: string })?.name === "AbortError") {
      throw new DownloadError("input_download_timeout", "Timeout ao baixar arquivo.");
    }
    throw new DownloadError("input_download_failed", "Falha ao baixar arquivo.");
  }
  if (!res.ok || !res.body) {
    clearTimeout(timer);
    if (res.status === 401 || res.status === 403) {
      throw new DownloadError("input_expired", "URL de download expirada.");
    }
    if ([429, 500, 502, 503, 504].includes(res.status)) {
      throw new DownloadError("input_download_transient", "Falha temporária ao baixar arquivo.");
    }
    throw new DownloadError("input_download_failed", "Falha ao baixar arquivo.");
  }

  let bytes = 0;
  const readable = Readable.fromWeb(res.body as never);
  const outStream = fs.createWriteStream(dest);
  try {
    await pipeline(async function* () {
      for await (const chunk of readable) {
        const buf = chunk as Buffer;
        bytes += buf.length;
        if (bytes > opts.maxBytes) {
          controller.abort();
          throw new DownloadError("input_too_large", "Arquivo excede tamanho máximo permitido.");
        }
        yield buf;
      }
    }, outStream);
  } catch (err) {
    clearTimeout(timer);
    try {
      fs.unlinkSync(dest);
    } catch {
      /* noop */
    }
    if (err instanceof DownloadError) throw err;
    throw new DownloadError("input_download_failed", "Falha ao baixar arquivo.");
  } finally {
    clearTimeout(timer);
  }

  if (bytes === 0) {
    try {
      fs.unlinkSync(dest);
    } catch {
      /* noop */
    }
    throw new DownloadError("input_empty", "Arquivo vazio.");
  }

  return { localPath: dest, bytes };
}

function extForMime(mime: string): string | null {
  switch ((mime || "").toLowerCase()) {
    case "video/mp4":
      return ".mp4";
    case "video/quicktime":
      return ".mov";
    case "video/webm":
      return ".webm";
    case "audio/mpeg":
      return ".mp3";
    case "audio/mp4":
      return ".m4a";
    case "audio/wav":
      return ".wav";
    case "image/png":
      return ".png";
    case "image/jpeg":
      return ".jpg";
    case "image/webp":
      return ".webp";
    case "image/svg+xml":
      return ".svg";
    default:
      return null;
  }
}

// ---------------------------------------------------------------------------
// ffprobe validation
// ---------------------------------------------------------------------------

export interface ProbeInfo {
  format: string;
  durationSeconds: number;
  width?: number;
  height?: number;
  hasAudio: boolean;
  hasVideo: boolean;
  videoCodec?: string;
  audioCodec?: string;
}

export async function ffprobe(file: string, ffprobeTimeoutMs = 15_000): Promise<ProbeInfo> {
  return new Promise((resolve, reject) => {
    const args = ["-v", "error", "-print_format", "json", "-show_format", "-show_streams", file];
    const child = spawn("ffprobe", args, { shell: false });
    let out = "";
    let err = "";
    const t = setTimeout(() => {
      child.kill("SIGKILL");
      reject(new DownloadError("ffprobe_timeout", "ffprobe demorou demais."));
    }, ffprobeTimeoutMs);
    child.stdout.on("data", (d) => (out += d.toString()));
    child.stderr.on("data", (d) => (err = (err + d.toString()).slice(-4096)));
    child.on("error", () => {
      clearTimeout(t);
      reject(new DownloadError("ffprobe_failed", "Falha ao inspecionar arquivo."));
    });
    child.on("close", (code) => {
      clearTimeout(t);
      if (code !== 0) {
        return reject(new DownloadError("ffprobe_failed", "Arquivo inválido."));
      }
      try {
        const parsed = JSON.parse(out) as {
          format?: { format_name?: string; duration?: string };
          streams?: Array<{
            codec_type?: string;
            codec_name?: string;
            width?: number;
            height?: number;
          }>;
        };
        const streams = parsed.streams ?? [];
        const v = streams.find((s) => s.codec_type === "video");
        const a = streams.find((s) => s.codec_type === "audio");
        resolve({
          format: parsed.format?.format_name ?? "",
          durationSeconds: Number(parsed.format?.duration ?? 0) || 0,
          width: v?.width,
          height: v?.height,
          hasAudio: Boolean(a),
          hasVideo: Boolean(v),
          videoCodec: v?.codec_name,
          audioCodec: a?.codec_name,
        });
      } catch {
        reject(new DownloadError("ffprobe_failed", "Saída ffprobe inválida."));
      }
    });
  });
}

/**
 * Confirm the downloaded file's content roughly matches the declared MIME.
 * We rely on ffprobe rather than parsing raw bytes.
 */
export function assertMimeMatchesProbe(mime: string, info: ProbeInfo): void {
  const m = (mime || "").toLowerCase();
  if (m.startsWith("video/") && !info.hasVideo) {
    throw new DownloadError("mime_mismatch", "Arquivo declarado como vídeo não contém vídeo.");
  }
  if (m.startsWith("audio/") && !info.hasAudio) {
    throw new DownloadError("mime_mismatch", "Arquivo declarado como áudio não contém áudio.");
  }
  if (m.startsWith("image/") && !info.hasVideo) {
    // ffprobe reports single image as a video stream, so hasVideo should be true.
    throw new DownloadError("mime_mismatch", "Arquivo de imagem inválido.");
  }
}
