/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicWorkerWebhookRouteImport } from './routes/api/public/worker-webhook'
import { Route as ApiPublicWorkerVerifyOutputRouteImport } from './routes/api/public/worker-verify-output'
import { Route as ApiPublicWorkerRenewUploadRouteImport } from './routes/api/public/worker-renew-upload'
import { Route as ApiPublicWorkerRenewInputRouteImport } from './routes/api/public/worker-renew-input'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProjectsProjectIdResultsRouteImport } from './routes/_authenticated/projects.$projectId.results'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWorkerWebhookRoute = ApiPublicWorkerWebhookRouteImport.update({
  id: '/api/public/worker-webhook',
  path: '/api/public/worker-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerVerifyOutputRoute =
  ApiPublicWorkerVerifyOutputRouteImport.update({
    id: '/api/public/worker-verify-output',
    path: '/api/public/worker-verify-output',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerRenewUploadRoute =
  ApiPublicWorkerRenewUploadRouteImport.update({
    id: '/api/public/worker-renew-upload',
    path: '/api/public/worker-renew-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerRenewInputRoute =
  ApiPublicWorkerRenewInputRouteImport.update({
    id: '/api/public/worker-renew-input',
    path: '/api/public/worker-renew-input',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdResultsRoute =
  AuthenticatedProjectsProjectIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/api/public/worker-renew-input': typeof ApiPublicWorkerRenewInputRoute
  '/api/public/worker-renew-upload': typeof ApiPublicWorkerRenewUploadRoute
  '/api/public/worker-verify-output': typeof ApiPublicWorkerVerifyOutputRoute
  '/api/public/worker-webhook': typeof ApiPublicWorkerWebhookRoute
  '/projects/$projectId/results': typeof AuthenticatedProjectsProjectIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/api/public/worker-renew-input': typeof ApiPublicWorkerRenewInputRoute
  '/api/public/worker-renew-upload': typeof ApiPublicWorkerRenewUploadRoute
  '/api/public/worker-verify-output': typeof ApiPublicWorkerVerifyOutputRoute
  '/api/public/worker-webhook': typeof ApiPublicWorkerWebhookRoute
  '/projects/$projectId/results': typeof AuthenticatedProjectsProjectIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/api/public/worker-renew-input': typeof ApiPublicWorkerRenewInputRoute
  '/api/public/worker-renew-upload': typeof ApiPublicWorkerRenewUploadRoute
  '/api/public/worker-verify-output': typeof ApiPublicWorkerVerifyOutputRoute
  '/api/public/worker-webhook': typeof ApiPublicWorkerWebhookRoute
  '/_authenticated/projects/$projectId/results': typeof AuthenticatedProjectsProjectIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/new'
    | '/api/public/worker-renew-input'
    | '/api/public/worker-renew-upload'
    | '/api/public/worker-verify-output'
    | '/api/public/worker-webhook'
    | '/projects/$projectId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/new'
    | '/api/public/worker-renew-input'
    | '/api/public/worker-renew-upload'
    | '/api/public/worker-verify-output'
    | '/api/public/worker-webhook'
    | '/projects/$projectId/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/api/public/worker-renew-input'
    | '/api/public/worker-renew-upload'
    | '/api/public/worker-verify-output'
    | '/api/public/worker-webhook'
    | '/_authenticated/projects/$projectId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicWorkerRenewInputRoute: typeof ApiPublicWorkerRenewInputRoute
  ApiPublicWorkerRenewUploadRoute: typeof ApiPublicWorkerRenewUploadRoute
  ApiPublicWorkerVerifyOutputRoute: typeof ApiPublicWorkerVerifyOutputRoute
  ApiPublicWorkerWebhookRoute: typeof ApiPublicWorkerWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/worker-webhook': {
      id: '/api/public/worker-webhook'
      path: '/api/public/worker-webhook'
      fullPath: '/api/public/worker-webhook'
      preLoaderRoute: typeof ApiPublicWorkerWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-verify-output': {
      id: '/api/public/worker-verify-output'
      path: '/api/public/worker-verify-output'
      fullPath: '/api/public/worker-verify-output'
      preLoaderRoute: typeof ApiPublicWorkerVerifyOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-renew-upload': {
      id: '/api/public/worker-renew-upload'
      path: '/api/public/worker-renew-upload'
      fullPath: '/api/public/worker-renew-upload'
      preLoaderRoute: typeof ApiPublicWorkerRenewUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker-renew-input': {
      id: '/api/public/worker-renew-input'
      path: '/api/public/worker-renew-input'
      fullPath: '/api/public/worker-renew-input'
      preLoaderRoute: typeof ApiPublicWorkerRenewInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/results': {
      id: '/_authenticated/projects/$projectId/results'
      path: '/results'
      fullPath: '/projects/$projectId/results'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdResultsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdResultsRoute: typeof AuthenticatedProjectsProjectIdResultsRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdResultsRoute:
      AuthenticatedProjectsProjectIdResultsRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicWorkerRenewInputRoute: ApiPublicWorkerRenewInputRoute,
  ApiPublicWorkerRenewUploadRoute: ApiPublicWorkerRenewUploadRoute,
  ApiPublicWorkerVerifyOutputRoute: ApiPublicWorkerVerifyOutputRoute,
  ApiPublicWorkerWebhookRoute: ApiPublicWorkerWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
